# Change these first
owner: GoodSay # Your GitHub organization or username, where this repository lives
repo: t # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: R-1
    url: 51.210.128.134:5000/api/health
  - name: R-2
    url: 51.210.128.134:5005/api/health
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
    
assignees: # Users to assign downtime issues (optional)
  - AnandChowdhary
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /t
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RD
  introTitle: TD
  introMessage: LD
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
